services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: vireka-api
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /data/postgres
    ports:
      - "9876:5432"
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
